### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@xpan-eileen this fix is not nice but it's what we need: the tests are always run as if GAP was executed in a terminal set to a width of 80 characters, and GAP then automatically wraps the printed output... there are some things one can do to make this a little bit nicer, but doing this everywhere will be quite a bit of work, so let's do this for now.

**Comment by fingolfin** [comment]
oh actually I think I can make it at least a bit nicer, wait a moment (we should wait anyway to verify it fixes the CI tests)

**Comment by fingolfin** [comment]
Because we run the tests with an option that tells it to ignore whitespace, we can actually undo the line breaks inserted by GAP resp. by `rewriteToFile:=true`, and see that the actual problem was a missing `.` ;-)

**Comment by xpan-eileen** [comment]
Thanks! The punctuation also just was wrong, so I am gonna change it a bit more...

**Comment by fingolfin** [comment]
By the way, this is also why for GAP we do *all* development through PRs, we never push directly to the master branch: this way, CI tests are run on all tests, including those which "surely cannot break anything" (and then inevitably break something after all ;-) )

**Pull request closed without merging**
